pipeline {
    agent any

    environment {
        DOCKER_IMAGE   = "leehk9311/final_hotel"
        SERVER_IP      = "52.78.28.91"
        CONTAINER_NAME = "final-hotel"
    }

    tools {
        jdk 'jdk17'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Gradle') {
		    steps {
		        dir('Final_hotel') {
		            sh 'chmod +x ./gradlew'
		            sh './gradlew clean build -x test'
		        }
		    }
		}

        stage('Docker Build & Push') {
		    steps {
		        dir('Final_hotel') {
		            withCredentials([usernamePassword(
		                credentialsId: 'dockerhub_info',
		                usernameVariable: 'DOCKER_USER',
		                passwordVariable: 'DOCKER_PASS'
		            )]) {
		                sh '''
		                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
		                    docker build -t $DOCKER_IMAGE:latest .
		                    docker push $DOCKER_IMAGE:latest
		                    docker logout || true
		                '''
		            }
		        }
		    }
		}

        stage('Deploy to Server') {
		    steps {
		        sshagent(['SERVER_SSH_KEY']) {
		            sh """
		                ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP '
		                    cd ~/app
		                    docker pull $DOCKER_IMAGE:latest
		                    docker compose down
		                    docker compose up -d
		                '
		            """
		        }
		    }
		}
    }

    post {
        success {
            echo "Deployment completed successfully."
        }
        failure {
            echo "Deployment failed."
        }
    }
}