pipeline {
    agent any

    environment {
        DOCKER_IMAGE   = "leehk9311/final_hotel"
        SERVER_IP      = "13.125.241.228"
        CONTAINER_NAME = "final-hotel"
    }

    tools {
        jdk 'jdk17'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Gradle') {
		    steps {
		        dir('Final_hotel') {
		            sh 'chmod +x ./gradlew'
		            sh './gradlew clean build -x test'
		        }
		    }
		}

        stage('Docker Build & Push') {
		    steps {
		        dir('Final_hotel') {
		            withCredentials([usernamePassword(
		                credentialsId: 'dockerhub_info',
		                usernameVariable: 'DOCKER_USER',
		                passwordVariable: 'DOCKER_PASS'
		            )]) {
		                sh '''
		                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
		                    docker build -t $DOCKER_IMAGE:latest .
		                    docker push $DOCKER_IMAGE:latest
		                    docker logout || true
		                '''
		            }
		        }
		    }
		}

        stage('Deploy to Server') {
            steps {
                sshagent(['SERVER_SSH_KEY']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP '
                            docker stop $CONTAINER_NAME || true
                            docker rm $CONTAINER_NAME || true
                            docker pull $DOCKER_IMAGE:latest
                            docker run -d --name $CONTAINER_NAME --restart unless-stopped -p 8001:9081 $DOCKER_IMAGE:latest
                        '
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Deployment completed successfully."
        }
        failure {
            echo "Deployment failed."
        }
    }
}