spring:
  profiles:
    active: prod

  datasource-finalorauser1:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbcUrl: jdbc:oracle:thin:@oracle:1521:xe
    username: final_orauser1
    password: sistsix
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000